### ISSUE TITLE
JSON embedded format, in preparation for v3

### ISSUE THREAD

**Issue by xaviered** [grongor/php-kafka-rest-client#7]
Given that [V3 preview is out](https://docs.confluent.io/current/kafka-rest/api.html#rest-proxy-v3) ...
1) Do you have plans to add V3 support?

2) Would you consider fully moving to JSON embedded format for on your V2, since that is what V3 is moving towards?
```
The v3 Admin APIs use the JSON:API specification. The Content-Type for both request and response of these APIs is application/vnd.api+json.
```

**Comment by grongor** [comment]
Hello,

since there are issues with the REST proxy that no-one seems to care about (https://github.com/confluentinc/kafka-rest/issues/597 and https://github.com/confluentinc/kafka-rest/issues/596 , plus many more), I don't know if I will add the support for V3. Maybe if they redesign the application completely, so that there would be a chance for these issues to be fixed. I'll decide when the V3 is out.

As for JSON embedded format support, I don't think it makes sense. It's just overhead...if it's mandatory for V3 then we will see when V3 is out, as I mentioned above.

**Comment by grongor** [comment]
I checked the docs now, and it seems nothing regarding the consumers is changing...so no, at the moment I plan no support for it until the issues are resolved. Because if those issues are not resolved then the REST proxy is useless.

**Comment by xaviered** [comment]
Thank you for your feedback on this. It definitely sounds like those two Kafka fixes are a must.
